include: https://gitlab/Sensirion/Python/ci-config-python/raw/master/gitlab-ci-template-v1.yml

check_rst_syntax:
  extends: .check_rst_syntax_v1
  script:
    - rst-lint *.rst


py2p7_linux_build_v1:
  extends: .py2p7_linux_build_v1

py3p5_linux_build_v1:
  extends: .py3p5_linux_build_v1


py2p7_32bit_win_build_v1:
  extends: .py2p7_32bit_win_docker_build_v1

py3p5_64bit_win_build_v1:
  extends: .py3p5_64bit_win_docker_build_v1


deploy_staging_v1:
  extends: .deploy_staging_v1

deploy_stable_v1:
  extends: .deploy_stable_v1
