name: Publish Documentation
on:
  push:
    branches:
      - master
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+"

jobs:
  documentation:
      uses: sensirion/.github/.github/workflows/driver.python.documentation.yml@main
      with:
        run-environment: "ubuntu-20.04"
        build-python-version: 3.6
